# Generated by Django 5.2.13 on 2026-04-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('recheio', models.CharField(blank=True, max_length=100, verbose_name='Recheio')),
                ('categoria', models.CharField(choices=[('Bolo', 'Bolo'), ('Doce', 'Doce'), ('Torta', 'Torta'), ('Cupcake', 'Cupcake'), ('Outro', 'Outro')], max_length=20, verbose_name='Categoria')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço por KG (R$)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
    ]
